name: api test

on:
  push:

jobs:
  with-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stepci/stepci@main
        with:
          workflow: workflow.yml

  with-vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - name: vitest
        run: yarn test
